---
title: "Day4 Problem Set"
author: "Cecilia Sui"
date: "1/13/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Day 4 Outline:
1. Types of Statistical Data (numerical, categorical, ordinal)
2. Probability distributions: rnorm / dnorm / pnorm / qnorm
3. Descriptive Statistics


# Probability Distributions

1. Suppose the height of males at a certain school is normally distributed with a mean of $\mu=168$ cm and a standard deviation of $\sigma = 9$ cm. Approximately what percentage of males at this school are **taller** than 175 cm?

2. Suppose the weight of a certain species of dogs is normally distributed with a mean of $\mu=33$ lbs  and a standard deviation of $\sigma = 5.5$ lbs. Approximately what percentage of this species of otters weight less than 28 lbs?


3. Suppose the height of flowers in a certain region is normally distributed with a mean of $\mu=24$ cm  and a standard deviation of $\sigma= 5$ cm. Approximately what percentage of flowers in this region are **between 18 and 25 cm** tall?


4. Find the Z-score of the 99th quantile of the standard normal distribution. 

5. Find the Z-score of the 95th quantile of the standard normal distribution. 

6. Generate a vector of 5 normally distributed random variables with mean = 10 and sd = 2

7. Generate a vector of 1000 normally distributed random variables with mean = 50 and sd = 5

8. Generate a vector of 1000 normally distributed random variables with mean = 50 and sd = 25


9. Generate two histograms using the **hist()** function to view these two distributions. 



\newpage
